# 조원분들 필수로 읽어 주세요.
# yml의 종류가 3가지라 당황스러우실 건데 저희가 github로 올리기에 보안상 문제가 되는 것들이 있습니다.
# 그래서 github에 올라가야 하는것들과 올라가지 말아야 하는 것들 구분해서 올리고자 생성했습니다.

# gitgnore로 들어가시면 application-secret.yml 있을겁니다. 그것만 github에 못올리게 조치 했습니다.
# secret.yml 에 올려야 하는것들 대충 몇가지 써놓겠습니다.

# 1. REST API 키 (소셜로그인 서비스 도입시 받는 인증 키입니다.)
# 2. 결제서비스 도입시 받는 키
# 3. 사용자 개인정보

#등등 이곳에 올려서 써주시면 됩니다!
#그리고 default 는 이곳 secret랑 똑같이는 셋팅 하되 키는 가리고 설정해서 올릴겁니다!
spring:
  mail:
  host: smtp.gmail.com
  port: 587
  username: winter001110@gmail.com
  password: puofrxedultxqtul
  properties:
    mail:
      smtp:
        auth: true
        starttls:
          enable: true
          required: true
        connectiontimeout: 5000
        timeout: 5000
        writetimeout: 5000
  auth-code-expiration-millis: 1800000  # 30 * 60 * 1000 == 30분
